artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gagan-bajwa/data/raw/main/Training_Batch_Files.zip # url from raw button of github --> righhtclick --> copy link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  source_dir: artifacts/data_ingestion/Training_Batch_Files
  good_dir: artifacts/data_validation/good
  bad_dir: artifacts/data_validation/bad 

db_operations:
  source_dir: artifacts/data_validation/good
  db_dir: db_operations/database
  db_name: db_operations/database/cement.db
  training_dir: db_operations/training
  training_file: db_operations/training/input.csv

training:
  source_dir: db_operations/training/input.csv
  training_dir: Training
  local_training_file: Training/training.csv
  preprocessed_data_dir: Training/preprocessed
  preprocessed_data: Training/preprocessed_data.csv
  Models_dir: Training/models
  clustering_model: Training/models/clustering_model.joblib
  model_cluster0: Training/models/model_cluster0.joblib
  model_cluster1: Training/models/model_cluster1.joblib
  model_cluster2: Training/model/model_cluster2.joblib
  images: Training/images