artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gagan-bajwa/data/raw/main/Training_Batch_Files.zip # url from raw button of github --> righhtclick --> copy link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion